### PR TITLE
Recommend first non-PC party instead of "anyone" to avoid vote-splitting

### PR DESCRIPTION
**Pull request by andryou**
Moreso a suggestion but up to you! One case is Toronto—St. Paul's:

    lib: 34
    pc: 31
    ndp: 32
    grn: 3
    other: 1

With these projections so close, I think it's best to recommend LIB and not anyone (lib/ndp/green).

### CODE REVIEW

**Comment by kieran** [comment]
I'd love to keep the "anyone" option - maybe just tighten it up a bit? Like `20%` or lower, and remove the "3rd or worse place" clause (`pcIndex > 1 or ...`)

```coffee
pcIndex = findIndex(sorted, { name: 'pc' })	
if sorted[pcIndex]['value'] < 20
  return parties['anyone']
```

**Comment by kieran** [comment]
I'd like to preserve non-strategic voting when at all possible

**Comment by andryou** [comment]
20% sounds good to me! I was looking through the final projection data and while 25% would work, there are one or two instances where the "anyone" suggestion might promote vote splitting. One example is Spadina—Fort York:

37.0 LIB
22.6 PC
37.4 NDP

Added in a new commit re-adding the anyone asset and your suggested logic.

**Comment by kieran** [comment]
Thanks, merged!

**Comment by andryou** [comment]
Just to illustrate the two vote split scenarios with a 25% threshold (so the 20% you suggested works perfectly):

**Pull request merged**
